Repository travel-news-feed/travel-news-feed, pull requests merged in 2024-02, with the labels that each got.

#18 Issue 12 feature
  build.gradle
  src/main/java/com/sparta/travelnewsfeed/controller/CommentController.java
  src/main/java/com/sparta/travelnewsfeed/dto/request/CommentCreateRequestDto.java
  src/main/java/com/sparta/travelnewsfeed/dto/request/CommentUpdateRequestDto.java
  src/main/java/com/sparta/travelnewsfeed/dto/request/PostCreateRequestDto.java
  src/main/java/com/sparta/travelnewsfeed/dto/response/CommentResponseDto.java
  src/main/java/com/sparta/travelnewsfeed/dto/response/PostReadResponseDto.java
  src/main/java/com/sparta/travelnewsfeed/entity/Comment.java
  src/main/java/com/sparta/travelnewsfeed/entity/Post.java
  src/main/java/com/sparta/travelnewsfeed/entity/User.java
  src/main/java/com/sparta/travelnewsfeed/repository/CommentRepository.java
  src/main/java/com/sparta/travelnewsfeed/repository/PostRepository.java
  src/main/java/com/sparta/travelnewsfeed/service/CommentService.java
  src/main/java/com/sparta/travelnewsfeed/service/UserService.java
Labels: enhancement, feature

#21 Issue-19-feature
  build.gradle
  src/main/java/com/sparta/travelnewsfeed/config/WebSecurityConfig.java
  src/main/java/com/sparta/travelnewsfeed/controller/PostController.java
  src/main/java/com/sparta/travelnewsfeed/controller/UserController.java
  src/main/java/com/sparta/travelnewsfeed/dto/request/LoginRequestDto.java
  src/main/java/com/sparta/travelnewsfeed/dto/request/PostUpdateRequestDto.java
  src/main/java/com/sparta/travelnewsfeed/dto/request/SignupRequestDto.java
  src/main/java/com/sparta/travelnewsfeed/dto/request/UserRequestDto.java
  src/main/java/com/sparta/travelnewsfeed/dto/response/CommonResponseDto.java
  src/main/java/com/sparta/travelnewsfeed/dto/response/PostUpdateResponseDto.java
  src/main/java/com/sparta/travelnewsfeed/dto/response/UserResponseDto.java
  src/main/java/com/sparta/travelnewsfeed/entity/Post.java
  src/main/java/com/sparta/travelnewsfeed/entity/common/DateTime.java
  src/main/java/com/sparta/travelnewsfeed/jwt/JwtAuthenticationFilter.java
  src/main/java/com/sparta/travelnewsfeed/jwt/JwtAuthorizationFilter.java
  src/main/java/com/sparta/travelnewsfeed/jwt/JwtUtil.java
  src/main/java/com/sparta/travelnewsfeed/repository/PostRepository.java
  src/main/java/com/sparta/travelnewsfeed/repository/UserRepository.java
  src/main/java/com/sparta/travelnewsfeed/service/PostService.java
  src/main/java/com/sparta/travelnewsfeed/service/UserService.java
  src/main/java/com/sparta/travelnewsfeed/user/User.java
  src/main/java/com/sparta/travelnewsfeed/user/UserDetailsImpl.java
  src/main/java/com/sparta/travelnewsfeed/user/UserDetailsServiceImpl.java
Labels: bug, enhancement, feature

#15 issue-14-enhancement
  src/main/java/com/sparta/travelnewsfeed/controller/PostController.java
  src/main/java/com/sparta/travelnewsfeed/dto/request/PostUpdateRequestDto.java
  src/main/java/com/sparta/travelnewsfeed/dto/response/PostUpdateResponseDto.java
  src/main/java/com/sparta/travelnewsfeed/entity/common/DateTime.java
  src/main/java/com/sparta/travelnewsfeed/service/PostService.java
Labels: enhancement

#25 Issue 22 feature
  src/main/java/com/sparta/travelnewsfeed/config/WebSecurityConfig.java
  src/main/java/com/sparta/travelnewsfeed/controller/PostController.java
  src/main/java/com/sparta/travelnewsfeed/controller/UserController.java
  src/main/java/com/sparta/travelnewsfeed/dto/request/SignupRequestDto.java
  src/main/java/com/sparta/travelnewsfeed/dto/request/UserRequestDto.java
  src/main/java/com/sparta/travelnewsfeed/jwt/JwtAuthenticationFilter.java
  src/main/java/com/sparta/travelnewsfeed/repository/PostRepository.java
  src/main/java/com/sparta/travelnewsfeed/service/PostService.java
  src/main/java/com/sparta/travelnewsfeed/service/UserService.java
  src/main/java/com/sparta/travelnewsfeed/user/User.java
Labels: bug, enhancement, feature
